In [1]:
import numpy as np
import time

# VECTORS - ONE DIM ARRAY - with elements

# (4,) is 1-dimenzional array with 4 elements, but for example (4,1) is 2-dim array with 4 ROWS and 1 COLUMN

In [2]:
#Vector Creation

# NumPy routines which allocate memory and fill arrays with value --> decimal values

a = np.zeros(4); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

# (4,) is 1-dimenzional array, but for example (4,1) is 2-dim array

np.zeros(4) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4) :  a = [0.46260998 0.25839795 0.23539538 0.8132867 ], a shape = (4,), a data type = float64


# 4. is a float number, and 4 is a int number

In [4]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
# get the number from 0 to 4 (without 4) - decimal values
a = np.arange(4.); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
#get 4 random number from 0 to 1
a = np.random.rand(4); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :  a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.zeros(4) :  a = [0.39493514 0.91022975 0.5234967  0.88451892], a shape = (4,), a data type = float64


# a = np.array([5,4,3,2]) is a 1 dim array with 4 elements or vector [5,4,3,2]

In [30]:
# NumPy routines which allocate memory and fill with user specified values

# int array 
a = np.array([5,4,3,2]); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
#decimal array - if only one number is decimal it cast all number from int to decimal
a = np.array([5.,4,3,2]); print(f"np.zeros(4) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :  a = [5 4 3 2], a shape = (4,), a data type = int32
np.zeros(4) :  a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [7]:
#Operations on Vectors
#get the int array because we set 10 not 10.
a = np.arange(10)
print(a)

#Access an element - a[index], last element a[-1]

print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}, Accesing an element returns a scalar")

#Access the last element

print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error

try:
    c = a[10]
except Exception as e:
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, Accesing an element returns a scalar
a[-1] = 9
index 10 is out of bounds for axis 0 with size 10


In [8]:
#Slicing (start:stop:step)
#get the int array because we set 10 not 10.
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
#from index 2 to 7 by 1 --> 2 3 4 5 6 - without 7
c = a[2:7:1]; print("a[2:7:1] =", c)

#access 3 elements separated by two
#from index 2 to 7 by 2 --> 2 4 6
c = a[2:7:2]; print("a[2:7:2]=", c)

#access all elements index 3 and above
#from index 3 to the end - with end and with index 3
c = a[3:]; print("a[3:] = ", c)


#access all elements below index 3
#from index 0 to 3 --> 0 1 2 - without 3
c = a[:3]; print("a[:3] = ", c)

#access all elements

c = a[:]; print("a[:]", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2]= [2 4 6]
a[3:] =  [3 4 5 6 7 8 9]
a[:3] =  [0 1 2]
a[:] [0 1 2 3 4 5 6 7 8 9]


In [9]:
#Single vector operations

a = np.array([1,2,3,4])
print(f"a: {a}")
#negate elements of a
b = -a
print(f"b = -a : {b}")


#Sum all elements of a, returns a scalar

b = np.sum(a)
print(f"np.sum(a) : {b}")

b = np.mean(a)
print(f"np.mean(a) : {b}")

b = a**2
print(f"a**2: {b}")

a: [1 2 3 4]
b = -a : [-1 -2 -3 -4]
np.sum(a) : 10
np.mean(a) : 2.5
a**2: [ 1  4  9 16]


In [10]:
#Vector Vector element-wise operations

a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
#sum every element of a with every element of b - if the same size (in elements and shapes)
print(f"Binary operations work element wise (if same size): {a + b}")

Binary operations work element wise (if same size): [0 0 6 8]


In [11]:
#Mismatched vectors
# 1 dim array with 2 elements
c = np.array([1,2])

try:
    d = a + c

except Exception as e:
    print(e)

operands could not be broadcast together with shapes (4,) (2,) 


In [12]:
#Scalaer Vector Operations
#1 dim array with 4 elements
a = np.array([1,2,3,4])

#multiply a by a scalar
#every number in vector multiply by scalar
b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


In [13]:
#Vector to Vector dot product (multiplies the values in two vectors element-wise and then sums the result).
#without vectorization

def my_dot(a,b):
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [29]:
#Test 1-D
#i dont know how vectors are multiplied
# 1dim array with 4 elements
a = np.array([1,2,3,4])
print(a.shape)
b = np.array([-1, 4, 3, 2])
print(b.shape)
print(f"my_dot(a,b) = {my_dot(a,b)}")

(4,)
(4,)
my_dot(a,b) = 24


In [16]:
#Using numpy np.dot function - with vectorization

# test 1-D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

c = np.dot(a,b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [17]:
#Vectors vs Loops - compared times

np.random.seed(1)

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time() #capture start time
c = np.dot(a,b)
toc = time.time()

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

tic = time.time()  # capture start time
c = my_dot(a,b)
toc = time.time()  # capture end time

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")

del(a);del(b)  #remove these big arrays from memory

np.dot(a, b) =  2501072.5817
Vectorized version duration: 62.5091 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 6037.1032 ms 


# X = np.array([1,2,3,4]) --> 1 dim arrays with 4 elements

# X = np.array([[1], [2], [3], [4]]) -->create list of list where each inner list represents a row in 2dim array (array with rows and columns) --> 4 rows and 1 column



In [28]:
#Example - two vectors multiply and gets a number/scalar

X = np.array([[1], [2], [3], [4]]) #2 dim arrays with 4 rows and 1 column!!!! IMPORTANT
w = np.array([2]) #vector (array) not scalar!! 
c = np.dot(X[1], w) #[2] by [2] is 4
print(f"c = {c}")
print(f"X[1] has shape {X[1].shape}")
print(f"X has shape {X.shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

c = 4
X[1] has shape (1,)
X has shape (4, 1)
w has shape (1,)
c has shape ()
X has shape (4,)


# MATRICES - TWO DIM ARRAYS (with rows and columns)

In [21]:
#Matrices

#Creation
#1 row and 5 columns
a = np.zeros((1,5))
print(f"a shape = {a.shape}, a = {a}")

#2 rows and 1 column
a = np.zeros((2,1))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((1,1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.]]


In [22]:
# NumPy routines which allocate memory and fill with user specified values
# get 3 rows and 1 column in 2dim array
a = np.array([[5], [4], [3]]); print(f"a shape = {a.shape}, np.array: a = {a}")

a = np.array([[5],  # One can also
              [4],  # separate values
              [3]]); #into separate rows
print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


# .reshape(3,2) --> reshape to 3 rows and 2 columns

In [26]:
#Operatioins on Matrices
#reshape to 3 rows and 2 columns
a = np.arange(6).reshape(3,2)
print(f"a.shape: {a.shape}, \na = {a}")

#Access an element
#name[row, column] --> return scalar
print(f"\na[2,0].shape: {a[2,0].shape}, a[2,0] = {a[2,0]}, type(a[2,0]) = {type(a[2,0])} Accessing an element returns a scalar\n")

#Access a row
#name[row] --> give us 1 vector (ndarray)
#.shape and type() usable functions
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")

a.shape: (3, 2), 
a = [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4, type(a[2,0]) = <class 'numpy.int32'> Accessing an element returns a scalar

a[2].shape: (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


In [27]:
#Vector 2-D slicing operaations
# i have 20 numbers (from 0 to 19) 
#Numpy do this: 20:10=2 and that gives as 2 rows and 10 columns
a = np.arange(20). reshape(-1, 10)

print(f"a = \n {a}")

#Access 5 consecutive elements (start:stop:step):
#from row 0 get from index 2 to 7 by 1 (without 7)
print("a[0, 2:7:1] = ", a[0,2:7:1], "a[0,2:7:1].shape = ", a[0,2:7:1].shape, "a 1-D array")

#Access 5 consecutive elements in two rows (start:stop:step):
#for all rows get element from index 2 to 7 by 1 (without 7)
print("a[:, 2:7:1] = \n", a[:,2:7:1], "a[:,2:7:1].shape = ", a[:,2:7:1].shape, "a 1-D array")

#Access all elements

print("a[:,:]}", a[:,:], ", a[:,:].shape = ", a[:,:].shape)

#Access all elements in one row - in row with index 1

print("a[1,:]}", a[1,:], ", a[1,:].shape = ", a[1,:].shape, "a 1-D array")

#same as

print("a[1]}", a[1], ", a[1].shape = ", a[1].shape, "a 1-D array")


a = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] a[0,2:7:1].shape =  (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] a[:,2:7:1].shape =  (2, 5) a 1-D array
a[:,:]} [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] , a[:,:].shape =  (2, 10)
a[1,:]} [10 11 12 13 14 15 16 17 18 19] , a[1,:].shape =  (10,) a 1-D array
a[1]} [10 11 12 13 14 15 16 17 18 19] , a[1].shape =  (10,) a 1-D array
